runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6